### ISSUE TITLE
Support for Zen 3 (and older cpus) + upstreaming to kernel

### ISSUE THREAD

**Issue by DarkSwan86** [amd/amd_energy#10]
Hi @nchatrad !

I kindly ask if there are any plans to add other Zen 3 processors (and if possible also the older models). 

Until now, if you want to measure CPU power consumption, you need to install out-of-tree packages like [ZenPower3](https://git.exozy.me/a/zenpower3) or [Ryzen SMU](https://gitlab.com/leogx9r/ryzen_smu).

Also, there is a possibility to upstream these changes to the main Linux Kernel repository?

Thanks for all the works!

Regards,

Leonardo

**Comment by nchatrad** [comment]
Hi Leonardo,

we did upstream this module to the hwmon subsystem in linux kernel and due to some CVEs which prove a potential attack, we had to remove it from the upstream.

We do not have plans to support this for older generations or in the upstream.

**Comment by DarkSwan86** [comment]
Thanks for the answer, i'll continue to use the out of tree patches :)
