### ISSUE TITLE
Device table is missing support for some processors

### ISSUE THREAD

**Issue by dead-claudia** [amd/amd_energy#2]
I haven't actually tested this, but I looked through the PPRs and found in the data sheets that the [CPU support list](https://github.com/amd/amd_energy/blob/c4263c9dc1aa13b89f20078ddaa30a96302a4c88/amd_energy.c#L362-L369) appears considerably more restrictive than it should be. So far, here's what I've found (there's probably others, but I couldn't readily find them):

- Family 17h Model 01h
- Family 17h Model 08h
- Family 17h Model 18h
- Family 17h Model 20h
- Family 17h Model 60h
- Family 17h Model 71h
- Family 19h Model 21h
- Family 19h Model 51h

*Incidentally, this amounts to everything that's currently on https://www.amd.com/en/support/tech-docs?keyword=processor+programming+reference right now.*

**Comment by nchatrad** [comment]
Hi Claudia, The measurements on various client models (listed above) are not well calibrated. Hence, the support is given to models which are calibrated and tested.

**Comment by dead-claudia** [comment]
Oh, okay. Thanks for the quick heads up!
