### ISSUE TITLE
Raphael support

### ISSUE THREAD

**Issue by cyring** [amd/amd_energy#9]
Hello,

Does Raphael support RAPL ?

With a 7950X we are reading those units:
```console
rdmsr -a 0xc0010299
a1000
...
a1000
```

Do you know why Power Unit `PU` is left to zero ?

**Comment by sumachidanand** [comment]
Hi,

As per Raphael processor reference manual [Processor Programming Reference (PPR) for AMD Family 19h Model 61h, Revision B1 Processors](https://www.amd.com/content/dam/amd/en/documents/processor-tech-docs/programmer-references/56713-B1_3_05.zip), following RAPL registers are supported.

**MSRC001_0299 (L3::L3CT::L3RAPLPowerUnit0)
MSRC001_029B (L3::L3CT::L3PackageEnergyStatus)**

But these registers provide energy information. So PowerUnits is read as 0 and EnergyUnits is having a valid value. 

amd_energy driver is mainly for server socs, not tested on desktop socs like Raphael.

Thank you

**Comment by cyring** [comment]
Thanks for this answer
